function [population_names, response_dimension, population_number] = load_population_names()
%load_population_names load population names for CMC
%   response_dimension: what appears on y-axis for neural response
        population_names = {'SS cells',...
            'conductance of spiny stellate cells',...
            'SP cells',...
            'conductance of superficial pyramidal cells',...
            'II',...
            'conductance of inhibitory interneurons',...
            'DP cells',...
            'conductance of deep pyramidal cells'};
        response_dimension = {'Scaled voltage (a.u.)', '', 'Scaled voltage (a.u.)', '', 'Scaled current (a.u.)', '', 'Scaled voltage (a.u.)', ''};
        population_number = [3 5];   % vector of neural populations to draw
end